## Masalah 1

In [1]:
import numpy as np

def reflexive_closure(n, M):
    """
    Menghitung closure refleksif dari relasi R pada himpunan S.
    Closure refleksif dicapai dengan mengubah semua elemen diagonal matriks menjadi 1.

    Args:
        n (int): Kardinalitas himpunan S.
        M (np.array): Matriks representasi relasi R (berukuran n x n).

    Returns:
        np.array: Matriks yang merepresentasikan closure refleksif dari R.
    """
    # Membuat salinan matriks agar tidak memodifikasi matriks asli
    R_reflexive = M.copy()
    # Mengatur semua elemen diagonal menjadi 1
    np.fill_diagonal(R_reflexive, 1)
    return R_reflexive

def symmetric_closure(n, M):
    """
    Menghitung closure simetris dari relasi R pada himpunan S.
    Untuk setiap pasangan (i, j) yang bernilai 1, pastikan sel (j, i) juga bernilai 1.
    Ini setara dengan menggabungkan M dengan transposenya (M U M^T).

    Args:
        n (int): Kardinalitas himpunan S.
        M (np.array): Matriks representasi relasi R (berukuran n x n).

    Returns:
        np.array: Matriks yang merepresentasikan closure simetris dari R.
    """
    # Membuat salinan matriks
    R_symmetric = M.copy()
    # Menambahkan elemen (j,i) jika (i,j) ada.
    # Ini dapat dicapai dengan operasi OR bitwise antara M dan transposenya.
    R_symmetric = R_symmetric | R_symmetric.T
    return R_symmetric

def transitive_closure(n, M):
    """
    Menghitung closure transitif dari relasi R pada himpunan S menggunakan
    Algoritma Warshall.
    Jika ada jalur dari a ke b dan dari b ke c, maka harus ada jalur dari a ke c.

    Args:
        n (int): Kardinalitas himpunan S.
        M (np.array): Matriks representasi relasi R (berukuran n x n).

    Returns:
        np.array: Matriks yang merepresentasikan closure transitif dari R.
    """
    # Membuat salinan matriks untuk working matrix
    R_transitive = M.copy()

    # Iterasi melalui setiap kemungkinan titik tengah 'k'
    for k in range(n):
        # Iterasi melalui setiap baris 'i'
        for i in range(n):
            # Iterasi melalui setiap kolom 'j'
            for j in range(n):
                # Jika ada relasi dari i ke k DAN dari k ke j,
                # maka harus ada relasi dari i ke j.
                # Menggunakan OR bitwise (|) untuk logika "atau" (True jika salah satu True)
                R_transitive[i, j] = R_transitive[i, j] | (R_transitive[i, k] & R_transitive[k, j])
    return R_transitive

# --- Contoh Penggunaan Masalah 1 ---
if __name__ == "__main__":
    # 1. Kardinalitas Himpunan S
    cardinality_S = 4
    # Merepresentasikan Himpunan S dengan set (untuk demonstrasi, tidak digunakan langsung dalam operasi matriks)
    S = set(range(cardinality_S))
    print(f"Himpunan S: {S}")

    # 2. Matriks Relasi R pada S
    # Contoh relasi R: (0,1), (1,2), (2,0), (1,3)
    # Ini adalah contoh matriks relasi 4x4.
    # 1 merepresentasikan relasi, 0 merepresentasikan tidak ada relasi.
    R_matrix = np.array([
        [0, 1, 0, 0],
        [0, 0, 1, 1],
        [1, 0, 0, 0],
        [0, 0, 0, 0]
    ], dtype=int) # Penting untuk dtype=int, jika tidak, operasi bitwise akan error

    print("\nMatriks Relasi Asli R:")
    print(R_matrix)

    # 1. Closure Refleksif
    R_reflexive = reflexive_closure(cardinality_S, R_matrix)
    print("\nMatriks Closure Refleksif R* (R_ref):")
    print(R_reflexive)

    # 2. Closure Simetris
    R_symmetric = symmetric_closure(cardinality_S, R_matrix)
    print("\nMatriks Closure Simetris R^s (R_sym):")
    print(R_symmetric)

    # 3. Closure Transitif
    R_transitive = transitive_closure(cardinality_S, R_matrix)
    print("\nMatriks Closure Transitif R^t (R_trans):")
    print(R_transitive)

    # Contoh gabungan: Transitive Closure of Symmetric Closure
    print("\nTransitive Closure of Symmetric Closure (R_sym)^t:")
    R_sym_then_trans = transitive_closure(cardinality_S, R_symmetric)
    print(R_sym_then_trans)

    # Contoh gabungan: Transitive Closure of Reflexive Closure
    print("\nTransitive Closure of Reflexive Closure (R_ref)^t:")
    R_ref_then_trans = transitive_closure(cardinality_S, R_reflexive)
    print(R_ref_then_trans)

    # Contoh gabungan: Transitive Closure of Reflexive and Symmetric Closure
    print("\nTransitive Closure of Reflexive and Symmetric Closure (R_ref_sym)^t:")
    R_ref_sym = symmetric_closure(cardinality_S, R_reflexive) # Reflexive lalu Symmetric
    R_ref_sym_then_trans = transitive_closure(cardinality_S, R_ref_sym)
    print(R_ref_sym_then_trans)


Himpunan S: {0, 1, 2, 3}

Matriks Relasi Asli R:
[[0 1 0 0]
 [0 0 1 1]
 [1 0 0 0]
 [0 0 0 0]]

Matriks Closure Refleksif R* (R_ref):
[[1 1 0 0]
 [0 1 1 1]
 [1 0 1 0]
 [0 0 0 1]]

Matriks Closure Simetris R^s (R_sym):
[[0 1 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [0 1 0 0]]

Matriks Closure Transitif R^t (R_trans):
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]]

Transitive Closure of Symmetric Closure (R_sym)^t:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Transitive Closure of Reflexive Closure (R_ref)^t:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 1]]

Transitive Closure of Reflexive and Symmetric Closure (R_ref_sym)^t:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


##Masalah 2

In [2]:
import heapq # Untuk Algoritma Prim (priority queue)

# --- REPRESENTASI GRAF ---
# Untuk Masalah 2, kita akan menggunakan adjacency list untuk Prim
# dan daftar edge untuk Kruskal.

# Kelas untuk merepresentasikan edge (sisi)
class Edge:
    def __init__(self, u, v, weight):
        """
        Inisialisasi objek Edge.
        Args:
            u (int): Titik awal (vertex).
            v (int): Titik akhir (vertex).
            weight (float): Bobot sisi.
        """
        self.u = u
        self.v = v
        self.weight = weight

    def __lt__(self, other):
        """
        Mendefinisikan perilaku kurang dari untuk perbandingan edge berdasarkan bobot.
        Digunakan oleh heapq (priority queue).
        """
        return self.weight < other.weight

    def __repr__(self):
        return f"({self.u}-{self.v}, w={self.weight})"

# --- ALGORITMA PRIM ---
def prim_mst(num_vertices, adjacency_list):
    """
    Mencari Pohon Pembangun Minimum (MST) menggunakan Algoritma Prim.

    Args:
        num_vertices (int): Jumlah total titik (vertex) dalam graf.
        adjacency_list (dict): Representasi graf sebagai adjacency list.
                                Format: {vertex: [(neighbor_vertex, weight), ...]}

    Returns:
        list: Daftar edge yang merupakan bagian dari MST.
        float: Total bobot MST.
    """
    mst_edges = [] # List untuk menyimpan edge-edge MST
    min_heap = []  # Priority queue untuk menyimpan edge-edge yang akan dieksplorasi
    visited = [False] * num_vertices # Melacak vertex yang sudah dikunjungi

    # Mulai dari vertex 0 (bisa vertex mana saja)
    start_vertex = 0
    visited[start_vertex] = True

    # Tambahkan semua edge dari start_vertex ke min_heap
    for neighbor, weight in adjacency_list.get(start_vertex, []):
        heapq.heappush(min_heap, Edge(start_vertex, neighbor, weight))

    total_weight = 0

    # Lanjutkan sampai semua vertex terkoneksi (atau min_heap kosong)
    while min_heap:
        # Ambil edge dengan bobot terkecil dari min_heap
        current_edge = heapq.heappop(min_heap)
        u, v, weight = current_edge.u, current_edge.v, current_edge.weight

        # Tentukan vertex mana yang baru akan dikunjungi
        new_vertex = -1
        if not visited[v]:
            new_vertex = v
        elif not visited[u]: # Kasus jika edge diambil dari v ke u (dari graf tak berarah)
            new_vertex = u

        if new_vertex != -1:
            visited[new_vertex] = True
            mst_edges.append(current_edge)
            total_weight += weight

            # Tambahkan semua edge dari new_vertex ke min_heap
            for neighbor, edge_weight in adjacency_list.get(new_vertex, []):
                if not visited[neighbor]:
                    heapq.heappush(min_heap, Edge(new_vertex, neighbor, edge_weight))

    # Pastikan semua vertex telah dikunjungi (untuk graf terhubung)
    if all(visited):
        return mst_edges, total_weight
    else:
        print("Graf tidak terhubung, MST tidak dapat ditemukan untuk semua vertex.")
        return [], 0


# --- ALGORITMA KRUSKAL ---
# Helper class untuk Disjoint Set Union (DSU) / Union-Find
class DSU:
    def __init__(self, n):
        """
        Inisialisasi struktur data Disjoint Set Union.
        parent[i] menyimpan parent dari i. rank[i] digunakan untuk optimasi union.
        """
        self.parent = list(range(n))
        self.rank = [0] * n

    def find(self, i):
        """
        Mencari root (representatif) dari set yang mengandung elemen i.
        Menggunakan path compression untuk optimasi.
        """
        if self.parent[i] == i:
            return i
        self.parent[i] = self.find(self.parent[i])
        return self.parent[i]

    def union(self, i, j):
        """
        Menggabungkan dua set yang mengandung elemen i dan j.
        Menggunakan union by rank untuk optimasi.
        Mengembalikan True jika union berhasil (yaitu, i dan j berada di set yang berbeda),
        False jika sudah di set yang sama.
        """
        root_i = self.find(i)
        root_j = self.find(j)

        if root_i != root_j:
            if self.rank[root_i] < self.rank[root_j]:
                self.parent[root_i] = root_j
            elif self.rank[root_j] < self.rank[root_i]:
                self.parent[root_j] = root_i
            else:
                self.parent[root_j] = root_i
                self.rank[root_i] += 1
            return True # Berhasil digabungkan
        return False # Sudah di set yang sama

def kruskal_mst(num_vertices, all_edges):
    """
    Mencari Pohon Pembangun Minimum (MST) menggunakan Algoritma Kruskal.

    Args:
        num_vertices (int): Jumlah total titik (vertex) dalam graf.
        all_edges (list): Daftar semua objek Edge dalam graf.

    Returns:
        list: Daftar edge yang merupakan bagian dari MST.
        float: Total bobot MST.
    """
    mst_edges = [] # List untuk menyimpan edge-edge MST
    total_weight = 0
    dsu = DSU(num_vertices) # Inisialisasi DSU untuk melacak set yang terhubung

    # Urutkan semua edge berdasarkan bobot secara menaik
    sorted_edges = sorted(all_edges, key=lambda edge: edge.weight)

    # Iterasi melalui edge yang sudah diurutkan
    for edge in sorted_edges:
        u, v, weight = edge.u, edge.v, edge.weight
        # Jika menambahkan edge ini tidak membentuk siklus (u dan v berada di set yang berbeda)
        if dsu.union(u, v):
            mst_edges.append(edge)
            total_weight += weight
            # Jika kita sudah mengumpulkan (num_vertices - 1) edge, MST sudah lengkap
            if len(mst_edges) == num_vertices - 1:
                break
    return mst_edges, total_weight


# --- Contoh Penggunaan Masalah 2 ---
if __name__ == "__main__":
    # Misalkan INA adalah graf lengkap dengan 38 titik
    # Kita akan menggunakan jumlah titik yang lebih kecil untuk contoh agar mudah dilihat.
    # Asumsikan 5 ibukota propinsi (0 sampai 4) untuk demonstrasi.
    num_provinces = 5 # Representasi 5 ibukota propinsi
    print(f"Jumlah ibukota propinsi (titik): {num_provinces}")

    # Contoh data graf (bisa diganti dengan jarak antar ibukota sesungguhnya)
    # Ini adalah representasi Adjacency List untuk Prim.
    # Graf lengkap berarti setiap titik terhubung dengan setiap titik lainnya.
    # Bobot sisi adalah jarak antar dua ibukota.
    # Contoh ini menggunakan bobot acak/predefined untuk demonstrasi.
    # Format: {vertex: [(neighbor, weight), ...]}
    adjacency_list_graph = {
        0: [(1, 2), (2, 5), (3, 1), (4, 6)],
        1: [(0, 2), (2, 3), (3, 4), (4, 7)],
        2: [(0, 5), (1, 3), (3, 5), (4, 8)],
        3: [(0, 1), (1, 4), (2, 5), (4, 9)],
        4: [(0, 6), (1, 7), (2, 8), (3, 9)]
    }

    # Untuk Kruskal, kita butuh daftar semua edge.
    # Kita akan membuat daftar edge unik (tanpa duplikat u-v dan v-u)
    all_edges_kruskal = []
    processed_edges = set() # Untuk mencegah duplikasi edge (u,v) dan (v,u)
    for u, neighbors in adjacency_list_graph.items():
        for v, weight in neighbors:
            # Pastikan hanya menambahkan edge sekali (misal, (u,v) tapi bukan (v,u) jika u < v)
            if (u, v) not in processed_edges and (v, u) not in processed_edges:
                all_edges_kruskal.append(Edge(u, v, weight))
                processed_edges.add((u, v))
                processed_edges.add((v, u)) # Tambahkan kedua arah untuk menandai sudah diproses


    print("\n--- Algoritma Prim ---")
    mst_prim_edges, mst_prim_weight = prim_mst(num_provinces, adjacency_list_graph)
    print("Edge-edge MST (Prim):")
    for edge in mst_prim_edges:
        print(f"  {edge}")
    print(f"Total Bobot MST (Prim): {mst_prim_weight} km")

    print("\n--- Algoritma Kruskal ---")
    mst_kruskal_edges, mst_kruskal_weight = kruskal_mst(num_provinces, all_edges_kruskal)
    print("Edge-edge MST (Kruskal):")
    for edge in mst_kruskal_edges:
        print(f"  {edge}")
    print(f"Total Bobot MST (Kruskal): {mst_kruskal_weight} km")

    # Verifikasi bahwa bobot MST sama
    if mst_prim_weight == mst_kruskal_weight:
        print("\nVerifikasi: Total bobot MST dari Prim dan Kruskal sama.")
    else:
        print("\nVerifikasi: Total bobot MST dari Prim dan Kruskal BERBEDA! Ada kesalahan.")



Jumlah ibukota propinsi (titik): 5

--- Algoritma Prim ---
Edge-edge MST (Prim):
  (0-3, w=1)
  (0-1, w=2)
  (1-2, w=3)
  (0-4, w=6)
Total Bobot MST (Prim): 12 km

--- Algoritma Kruskal ---
Edge-edge MST (Kruskal):
  (0-3, w=1)
  (0-1, w=2)
  (1-2, w=3)
  (0-4, w=6)
Total Bobot MST (Kruskal): 12 km

Verifikasi: Total bobot MST dari Prim dan Kruskal sama.


In [4]:
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visualisasi Algoritma MST</title>
    <!-- Tailwind CSS CDN -->
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- D3.js CDN -->
    <script src="https://d3js.org/d3.v7.min.js"></script>
    <style>
        /* Konfigurasi Tailwind CSS untuk font Inter */
        html, body {
            font-family: 'Inter', sans-serif;
            height: 100%;
            margin: 0;
            padding: 0;
            overflow-x: hidden; /* Mencegah scrolling horizontal */
        }
        /* Styling khusus untuk SVG */
        svg {
            display: block;
            margin: auto;
            border-radius: 0.5rem; /* Rounded corners */
        }
        .edge-label {
            font-size: 10px;
            fill: #4b5563; /* Warna teks abu-abu tua */
            user-select: none; /* Mencegah teks terseleksi */
        }
        .node-label {
            user-select: none; /* Mencegah teks terseleksi */
        }
    </style>
    <script>
        // Konfigurasi Tailwind CSS untuk Inter font
        tailwind.config = {
            theme: {
                extend: {
                    fontFamily: {
                        sans: ['Inter', 'sans-serif'],
                    },
                },
            },
        };
    </script>
</head>
<body class="bg-gray-50 flex items-center justify-center min-h-screen p-4">
    <div class="container mx-auto p-6 bg-white rounded-xl shadow-2xl max-w-4xl border border-gray-200">
        <h1 class="text-4xl font-extrabold text-center text-gray-800 mb-8 leading-tight">Visualisasi Algoritma Pohon Pembangun Minimum (MST)</h1>

        <div class="flex flex-col lg:flex-row justify-around items-stretch gap-8">
            <!-- Container untuk Prim -->
            <div class="w-full lg:w-1/2 bg-blue-50 p-6 rounded-lg shadow-inner border border-blue-200 flex flex-col items-center">
                <h2 class="text-2xl font-bold text-blue-700 mb-4">Algoritma Prim</h2>
                <div id="prim-graph-container" class="w-full h-80 sm:h-96 border border-blue-300 rounded-md bg-white overflow-hidden"></div>
                <p class="text-lg font-semibold text-gray-700 mt-4">Total Bobot MST Prim: <span id="prim-total-weight" class="font-extrabold text-blue-800">0</span> km</p>
            </div>

            <!-- Container untuk Kruskal -->
            <div class="w-full lg:w-1/2 bg-green-50 p-6 rounded-lg shadow-inner border border-green-200 flex flex-col items-center">
                <h2 class="text-2xl font-bold text-green-700 mb-4">Algoritma Kruskal</h2>
                <div id="kruskal-graph-container" class="w-full h-80 sm:h-96 border border-green-300 rounded-md bg-white overflow-hidden"></div>
                <p class="text-lg font-semibold text-gray-700 mt-4">Total Bobot MST Kruskal: <span id="kruskal-total-weight" class="font-extrabold text-green-800">0</span> km</p>
            </div>
        </div>

        <div class="flex justify-center mt-10">
            <button id="generate-mst-btn"
                    class="bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-700 hover:to-indigo-700
                           text-white font-extrabold py-3 px-8 rounded-full shadow-xl transition-all duration-300
                           transform hover:scale-105 active:scale-95 focus:outline-none focus:ring-4 focus:ring-purple-300">
                Generasi & Visualisasi MST
            </button>
        </div>

        <p class="text-sm text-gray-500 text-center mt-8">
            Catatan: Untuk demonstrasi, graf menggunakan 5 titik dengan bobot yang ditentukan.
            Algoritma Prim dan Kruskal akan menghitung dan memvisualisasikan Pohon Pembangun Minimum.
            Garis berwarna biru menunjukkan MST Kruskal, dan garis berwarna hijau menunjukkan MST Prim.
        </p>
    </div>

    <script>
        // --- Data Graf ---
        // Jumlah vertex (ibukota propinsi)
        const numVertices = 5;

        // Data node dengan posisi manual untuk tata letak yang jelas
        const nodesData = [
            { id: 0, x: 100, y: 100 }, // Posisi Node 0
            { id: 1, x: 300, y: 100 }, // Posisi Node 1
            { id: 2, x: 200, y: 250 }, // Posisi Node 2
            { id: 3, x: 100, y: 350 }, // Posisi Node 3
            { id: 4, x: 300, y: 350 }, // Posisi Node 4
        ];

        // Data edge dengan bobot (jarak)
        const edgesData = [
            { u: 0, v: 1, weight: 2 },
            { u: 0, v: 2, weight: 5 },
            { u: 0, v: 3, weight: 1 }, // Edge terbobot terkecil
            { u: 0, v: 4, weight: 6 },
            { u: 1, v: 2, weight: 3 },
            { u: 1, v: 3, weight: 4 },
            { u: 1, v: 4, weight: 7 },
            { u: 2, v: 3, weight: 5 },
            { u: 2, v: 4, weight: 8 },
            { u: 3, v: 4, weight: 9 },
        ];

        // --- Konversi ke Adjacency List untuk Algoritma Prim ---
        const adjacencyListPrim = {};
        for (let i = 0; i < numVertices; i++) {
            adjacencyListPrim[i] = [];
        }
        edgesData.forEach(edge => {
            adjacencyListPrim[edge.u].push({ neighbor: edge.v, weight: edge.weight });
            adjacencyListPrim[edge.v].push({ neighbor: edge.u, weight: edge.weight }); // Graf tak berarah
        });

        // --- Fungsi Penggambar Graf ---
        function drawGraph(containerId, mstEdges, totalWeight, highlightColor) {
            // Hapus gambar sebelumnya di dalam container
            d3.select(`#${containerId}`).selectAll("*").remove();

            // Buat elemen SVG baru
            const svg = d3.select(`#${containerId}`)
                .append("svg")
                .attr("width", "100%")
                .attr("height", "100%")
                // viewBox digunakan untuk penskalaan responsif
                .attr("viewBox", `0 0 400 450`); // Sesuaikan ukuran viewBox jika perlu

            // Gambar Edge (garis) terlebih dahulu (agar node berada di atasnya)
            const links = svg.selectAll("line")
                .data(edgesData)
                .enter()
                .append("line")
                .attr("x1", d => nodesData[d.u].x)
                .attr("y1", d => nodesData[d.u].y)
                .attr("x2", d => nodesData[d.v].x)
                .attr("y2", d => nodesData[d.v].y)
                .attr("stroke", "#e5e7eb") // Warna default abu-abu sangat muda
                .attr("stroke-width", 2.5)
                .attr("stroke-linecap", "round")
                .attr("class", "all-edges"); // Tambahkan kelas untuk seleksi

            // Gambar bobot Edge
            svg.selectAll(".edge-label")
                .data(edgesData)
                .enter()
                .append("text")
                .attr("class", "edge-label")
                .attr("x", d => (nodesData[d.u].x + nodesData[d.v].x) / 2)
                .attr("y", d => (nodesData[d.u].y + nodesData[d.v].y) / 2 - 8) // Sedikit di atas edge
                .attr("text-anchor", "middle")
                .text(d => d.weight);

            // Sorot Edge MST
            mstEdges.forEach(mstEdge => {
                // Cari edge yang cocok (baik u-v atau v-u)
                links.filter(d =>
                    (d.u === mstEdge.u && d.v === mstEdge.v) ||
                    (d.u === mstEdge.v && d.v === mstEdge.u)
                )
                .attr("stroke", highlightColor) // Warna sorotan
                .attr("stroke-width", 5) // Lebih tebal
                .raise(); // Pastikan edge ini di atas edge lain (jika ada tumpang tindih)
            });


            // Gambar Node (lingkaran) di atas edge
            const circles = svg.selectAll("circle")
                .data(nodesData)
                .enter()
                .append("circle")
                .attr("cx", d => d.x)
                .attr("cy", d => d.y)
                .attr("r", 18) // Radius node
                .attr("fill", "#6366f1") // Warna isi node (ungu)
                .attr("stroke", "#4338ca") // Warna border node (ungu tua)
                .attr("stroke-width", 3)
                .attr("class", "node"); // Tambahkan kelas

            // Tambahkan Label Node (ID)
            svg.selectAll("text.node-label")
                .data(nodesData)
                .enter()
                .append("text")
                .attr("class", "node-label")
                .attr("x", d => d.x)
                .attr("y", d => d.y + 6) // Sesuaikan posisi teks
                .attr("text-anchor", "middle")
                .attr("fill", "white")
                .attr("font-size", "14px")
                .attr("font-weight", "bold")
                .text(d => d.id);

            // Perbarui tampilan total bobot di HTML
            d3.select(`#${containerId.replace('graph-container', 'total-weight')}`).text(totalWeight);
        }

        // --- ALGORITMA PRIM (Implementasi JavaScript) ---
        // Kelas Pembantu untuk Edge Prim
        class PrimEdge {
            constructor(u, v, weight) {
                this.u = u;
                this.v = v;
                this.weight = weight;
            }
            // Diperlukan untuk perbandingan dalam min-heap
            valueOf() {
                return this.weight;
            }
        }

        function primMST_js(numVertices, adjList) {
            const mstEdges = [];
            // Menggunakan Array sebagai min-heap dan mengurutkan secara manual setelah push
            // Ini kurang efisien dibandingkan implementasi heap yang sebenarnya,
            // tetapi cukup untuk jumlah vertex yang kecil dan untuk demonstrasi.
            const minHeap = [];
            const visited = new Array(numVertices).fill(false); // Melacak vertex yang sudah dikunjungi

            let startVertex = 0; // Mulai dari vertex 0
            visited[startVertex] = true;

            // Tambahkan semua edge dari vertex awal ke minHeap
            for (const { neighbor, weight } of adjList[startVertex] || []) {
                minHeap.push(new PrimEdge(startVertex, neighbor, weight));
            }
            // Urutkan untuk memastikan elemen terkecil ada di awal
            minHeap.sort((a, b) => a.weight - b.weight);

            let totalWeight = 0;
            let edgesCount = 0;

            // Loop sampai semua vertex terkoneksi (atau minHeap kosong)
            while (minHeap.length > 0 && edgesCount < numVertices - 1) {
                const currentEdge = minHeap.shift(); // Ambil edge dengan bobot terkecil
                const u = currentEdge.u;
                const v = currentEdge.v;
                const weight = currentEdge.weight;

                let newVertex = -1;
                // Periksa apakah salah satu ujung edge adalah vertex yang sudah dikunjungi dan yang lain belum
                if (visited[u] && !visited[v]) {
                    newVertex = v;
                } else if (visited[v] && !visited[u]) {
                    newVertex = u;
                }

                if (newVertex !== -1) { // Jika ditemukan vertex baru
                    visited[newVertex] = true;
                    mstEdges.push(currentEdge); // Tambahkan edge ke MST
                    totalWeight += weight;
                    edgesCount++;

                    // Tambahkan semua edge dari newVertex ke minHeap
                    for (const { neighbor, weight: edgeWeight } of adjList[newVertex] || []) {
                        if (!visited[neighbor]) {
                            minHeap.push(new PrimEdge(newVertex, neighbor, edgeWeight));
                        }
                    }
                    // Urutkan kembali minHeap setelah menambahkan edge baru
                    minHeap.sort((a, b) => a.weight - b.weight);
                }
            }
            return { mstEdges, totalWeight };
        }


        // --- ALGORITMA KRUSKAL (Implementasi JavaScript) ---
        // Kelas Pembantu untuk Disjoint Set Union (DSU)
        class DSU_JS {
            constructor(n) {
                this.parent = Array.from({ length: n }, (_, i) => i); // Setiap elemen adalah parent dari dirinya sendiri
                this.rank = new Array(n).fill(0); // Digunakan untuk optimasi union by rank
            }

            find(i) {
                // Mencari root (representatif) dari set yang mengandung elemen i
                // Menggunakan path compression untuk optimasi
                if (this.parent[i] === i) {
                    return i;
                }
                this.parent[i] = this.find(this.parent[i]);
                return this.parent[i];
            }

            union(i, j) {
                // Menggabungkan dua set yang mengandung elemen i dan j
                // Menggunakan union by rank untuk optimasi
                let root_i = this.find(i);
                let root_j = this.find(j);

                if (root_i !== root_j) { // Jika keduanya belum berada di set yang sama
                    if (this.rank[root_i] < this.rank[root_j]) {
                        this.parent[root_i] = root_j;
                    } else if (this.rank[root_j] < this.rank[root_i]) {
                        this.parent[root_j] = root_i;
                    } else {
                        this.parent[root_j] = root_i;
                        this.rank[root_i] += 1;
                    }
                    return true; // Berhasil digabungkan
                }
                return false; // Sudah di set yang sama (menambahkan edge akan membentuk siklus)
            }
        }

        function kruskalMST_js(numVertices, allEdges) {
            const mstEdges = [];
            let totalWeight = 0;
            const dsu = new DSU_JS(numVertices); // Inisialisasi DSU

            // Urutkan semua edge berdasarkan bobot secara menaik
            // Buat salinan allEdges agar tidak mengurutkan array asli
            const sortedEdges = [...allEdges].sort((a, b) => a.weight - b.weight);

            // Iterasi melalui edge yang sudah diurutkan
            for (const edge of sortedEdges) {
                // Jika menambahkan edge ini tidak membentuk siklus (u dan v berada di set yang berbeda)
                if (dsu.union(edge.u, edge.v)) {
                    mstEdges.push(edge); // Tambahkan edge ke MST
                    totalWeight += edge.weight;
                    // Jika kita sudah mengumpulkan (numVertices - 1) edge, MST sudah lengkap
                    if (mstEdges.length === numVertices - 1) {
                        break;
                    }
                }
            }
            return { mstEdges, totalWeight };
        }

        // --- Event Listener untuk Tombol ---
        document.getElementById('generate-mst-btn').addEventListener('click', () => {
            // Jalankan Algoritma Prim
            const { mstEdges: primMstEdges, totalWeight: primTotalWeight } = primMST_js(numVertices, adjacencyListPrim);
            drawGraph('prim-graph-container', primMstEdges, primTotalWeight, '#22c55e'); // Warna hijau untuk Prim

            // Jalankan Algoritma Kruskal
            const { mstEdges: kruskalMstEdges, totalWeight: kruskalTotalWeight } = kruskalMST_js(numVertices, edgesData);
            drawGraph('kruskal-graph-container', kruskalMstEdges, kruskalTotalWeight, '#3b82f6'); // Warna biru untuk Kruskal
        });

        // Gambar awal saat halaman dimuat
        document.addEventListener('DOMContentLoaded', () => {
            // Picu klik tombol secara otomatis saat halaman dimuat
            document.getElementById('generate-mst-btn').click();
        });
    </script>
</body>
</html>


IndentationError: unindent does not match any outer indentation level (<tokenize>, line 73)