In [22]:
!pip install adjust texted

## Masalah 1 : Closure Relasi Simetris, Refleksif, Transitif 

In [ ]:
import numpy as np

def reflexive_closure(n, M):
    """
    Menghitung closure refleksif dari relasi R pada himpunan S.
    Closure refleksif dicapai dengan mengubah semua elemen diagonal matriks menjadi 1.

    Input:
        n (int): Kardinalitas himpunan S.
        M (np.array): Matriks representasi relasi R (berukuran n x n).

    Output:
        np.array: Matriks yang merepresentasikan closure refleksif dari R.
    """
    # Membuat salinan matriks agar tidak memodifikasi matriks asli
    R_reflexive = M.copy()
    # Mengatur semua elemen diagonal menjadi 1
    np.fill_diagonal(R_reflexive, 1)
    return R_reflexive

def symmetric_closure(n, M):
    """
    Menghitung closure simetris dari relasi R pada himpunan S.
    Untuk setiap pasangan (i, j) yang bernilai 1, pastikan sel (j, i) juga bernilai 1.
    Ini setara dengan menggabungkan M dengan transposenya (M U M^T).

    Input :
        n (int): Kardinalitas himpunan S.
        M (np.array): Matriks representasi relasi R (berukuran n x n).

    Output :
        np.array: Matriks yang merepresentasikan closure simetris dari R.
    """
    # Membuat salinan matriks
    R_symmetric = M.copy()
    # Menambahkan elemen (j,i) jika (i,j) ada.
    # Ini dapat dicapai dengan operasi OR bitwise antara M dan transposenya.
    R_symmetric = R_symmetric | R_symmetric.T
    return R_symmetric

def transitive_closure(n, M):
    """
    Menghitung closure transitif dari relasi R pada himpunan S menggunakan
    Algoritma Warshall.
    Jika ada jalur dari a ke b dan dari b ke c, maka harus ada jalur dari a ke c.

    Input :
        n (int): Kardinalitas himpunan S.
        M (np.array): Matriks representasi relasi R (berukuran n x n).

    Output :
        np.array: Matriks yang merepresentasikan closure transitif dari R.
    """
    # Membuat salinan matriks untuk working matrix
    R_transitive = M.copy()

    # Iterasi melalui setiap kemungkinan titik tengah 'k'
    for k in range(n):
        # Iterasi melalui setiap baris 'i'
        for i in range(n):
            # Iterasi melalui setiap kolom 'j'
            for j in range(n):
                # Jika ada relasi dari i ke k DAN dari k ke j,
                # maka harus ada relasi dari i ke j.
                # Menggunakan OR bitwise (|) untuk logika "atau" (True jika salah satu True)
                R_transitive[i, j] = R_transitive[i, j] | (R_transitive[i, k] & R_transitive[k, j])
    return R_transitive

# --- Contoh Penggunaan Masalah 1 ---

# 1. Kardinalitas Himpunan S
cardinality_S = 4
# Merepresentasikan Himpunan S dengan set (untuk demonstrasi, tidak digunakan langsung dalam operasi matriks)
S = set(range(cardinality_S))
print(f"Himpunan S: {S}")

# 2. Matriks Relasi R pada S
# Contoh relasi R: (0,1), (1,2), (2,0), (1,3)
# Ini adalah contoh matriks relasi 4x4.
# 1 merepresentasikan relasi, 0 merepresentasikan tidak ada relasi.
R_matrix = np.array([
    [0, 1, 0, 0],
    [0, 0, 1, 1],
    [1, 0, 0, 0],
    [0, 0, 0, 0]
], dtype=int) #  untuk dtype=int, jika tidak, operasi bitwise akan error

print("\nMatriks Relasi Asli R:")
print(R_matrix)

# 1. Closure Refleksif
R_reflexive = reflexive_closure(cardinality_S, R_matrix)
print("\nMatriks Closure Refleksif R* (R_ref):")
print(R_reflexive)

# 2. Closure Simetris
R_symmetric = symmetric_closure(cardinality_S, R_matrix)
print("\nMatriks Closure Simetris R^s (R_sym):")
print(R_symmetric)

# 3. Closure Transitif
R_transitive = transitive_closure(cardinality_S, R_matrix)
print("\nMatriks Closure Transitif R^t (R_trans):")
print(R_transitive)


Himpunan S: {0, 1, 2, 3}

Matriks Relasi Asli R:
[[0 1 0 0]
 [0 0 1 1]
 [1 0 0 0]
 [0 0 0 0]]

Matriks Closure Refleksif R* (R_ref):
[[1 1 0 0]
 [0 1 1 1]
 [1 0 1 0]
 [0 0 0 1]]

Matriks Closure Simetris R^s (R_sym):
[[0 1 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [0 1 0 0]]

Matriks Closure Transitif R^t (R_trans):
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]]
